// Curated reading shelf. Editions are resolved from the catalog by title + author (most downloaded wins).
//
// track: 'story' | 'novel' | 'nonfiction' measure their level from the text;
//        'poetry' | 'drama' need a teacher-set `level` because verse and scripts skew readability formulas.
// level: optional 1-5 override. copy: include in the 필사용 shelf.
// quote: a well-known line; kept only if it is found verbatim in the downloaded text.
export const SOURCES = [
  { title: 'The Tale of Peter Rabbit', author: 'Potter', track: 'story', reason: '말썽꾸러기 토끼 피터의 짧은 모험. 그림책 한 권 분량이라 원서 첫 경험으로 좋습니다.' },
  { title: "Aesop's Fables", author: 'Aesop', track: 'story', reason: '한두 쪽짜리 우화 모음. 하루 한 편씩 읽고 교훈을 영어로 말해 보기 좋습니다.' },
  { title: 'The Velveteen Rabbit', author: 'Bianco', track: 'story', reason: '아이의 사랑을 받아 진짜가 되고 싶은 헝겊 토끼 이야기. 짧고 따뜻합니다.' },
  { title: 'Just So Stories', author: 'Kipling', track: 'story', reason: '‘코끼리 코는 왜 길까?’ 같은 질문에 엉뚱하게 답하는 옛이야기 모음입니다.' },
  { title: "Grimms' Fairy Tales", author: 'Grimm', track: 'story', reason: '헨젤과 그레텔, 라푼젤 등 익숙한 동화를 영어 번역으로 읽습니다.' },
  { title: "Andersen's Fairy Tales", author: 'Andersen', track: 'story', reason: '인어공주, 미운 오리 새끼 같은 안데르센 동화를 한 편씩 끊어 읽을 수 있습니다.' },
  { title: 'The Wonderful Wizard of Oz', author: 'Baum', track: 'novel', quote: 'There is no place like home', reason: '도로시와 친구들의 여정. 문장이 쉽고 장면이 선명해 원서 입문용으로 많이 읽힙니다.' },
  { title: "Alice's Adventures in Wonderland", author: 'Carroll', track: 'novel', quote: 'Curiouser and curiouser!', reason: '말장난과 엉뚱한 논리가 가득한 고전. 소리 내어 읽으면 재미가 커집니다.' },
  { title: 'Through the Looking-Glass', author: 'Carroll', track: 'novel', reason: '거울 속 체스판 세계로 들어간 앨리스의 두 번째 모험입니다.' },
  { title: 'Peter Pan', author: 'Barrie', track: 'novel', quote: 'All children, except one, grow up.', reason: '자라지 않는 소년 피터 팬. 첫 문장부터 인상적인 판타지입니다.' },
  { title: 'The Secret Garden', author: 'Burnett', track: 'novel', reason: '버려진 정원을 되살리며 마음도 회복하는 아이들의 성장 이야기입니다.' },
  { title: 'A Little Princess', author: 'Burnett', track: 'novel', reason: '하루아침에 모든 것을 잃고도 품위를 지키는 소녀 세라의 이야기입니다.' },
  { title: 'The Jungle Book', author: 'Kipling', track: 'story', reason: '늑대에게 자란 소년 모글리와 정글 동물들의 이야기 모음입니다.' },
  { title: 'Black Beauty', author: 'Sewell', track: 'novel', reason: '말의 눈으로 쓴 소설. 1인칭 서술을 익히기 좋습니다.' },
  { title: 'Heidi', author: 'Spyri', track: 'novel', reason: '알프스 산골 소녀 하이디의 이야기. 자연 묘사가 풍부합니다.' },
  { title: 'Pollyanna', author: 'Porter', track: 'novel', reason: '무엇에서든 기뻐할 거리를 찾는 소녀 폴리애나의 이야기입니다.' },
  { title: 'The Call of the Wild', author: 'London', track: 'novel', reason: '썰매 개 벅이 야생의 본능을 되찾아 가는 짧고 강렬한 모험 소설입니다.' },
  { title: 'White Fang', author: 'London', track: 'novel', reason: '늑대개 화이트 팽이 사람과 관계를 맺어 가는 이야기. 『야성의 부름』과 짝을 이룹니다.' },
  { title: 'The Adventures of Tom Sawyer', author: 'Twain', track: 'novel', reason: '미시시피 강가 마을 소년 톰의 장난과 모험. 미국 구어체를 맛볼 수 있습니다.' },
  { title: 'Treasure Island', author: 'Stevenson', track: 'novel', quote: "Fifteen men on the dead man's chest", reason: '해적, 보물 지도, 배신이 이어지는 모험 소설의 원조입니다.' },
  { title: 'Anne of Green Gables', author: 'Montgomery', track: 'novel', reason: '상상력 넘치는 고아 소녀 앤의 성장기. 풍부한 형용사 표현을 익힐 수 있습니다.' },
  { title: 'Little Women', author: 'Alcott', track: 'novel', reason: '네 자매의 성장과 꿈을 그린 소설. 인물마다 말투가 달라 읽는 재미가 있습니다.' },
  { title: 'The Adventures of Sherlock Holmes', author: 'Doyle', track: 'story', reason: '단편 12편으로 된 추리 소설. 한 편씩 끊어 읽기 좋습니다.' },
  { title: 'The Hound of the Baskervilles', author: 'Doyle', track: 'novel', reason: '황무지의 전설과 사냥개를 둘러싼 셜록 홈스 장편입니다.' },
  { title: 'A Study in Scarlet', author: 'Doyle', track: 'novel', reason: '홈스와 왓슨이 처음 만나는 첫 번째 사건입니다.' },
  { title: 'The Time Machine', author: 'Wells', track: 'novel', reason: '시간 여행 기계로 먼 미래에 간 과학자의 이야기. 짧은 SF 고전입니다.' },
  { title: 'The War of the Worlds', author: 'Wells', track: 'novel', reason: '화성인의 지구 침공을 목격자의 눈으로 생생하게 기록한 SF입니다.' },
  { title: 'The Invisible Man', author: 'Wells', track: 'novel', reason: '투명 인간이 된 과학자의 몰락을 그린 짧은 장편입니다.' },
  { title: 'Around the World in Eighty Days', author: 'Verne', track: 'novel', reason: '80일 안에 세계를 일주하겠다는 내기. 여행지와 교통수단 어휘가 많습니다.' },
  { title: 'Twenty Thousand Leagues under the Sea', author: 'Verne', track: 'novel', reason: '잠수함 노틸러스호를 타고 떠나는 해저 탐험 소설입니다.' },
  { title: 'A Christmas Carol', author: 'Dickens', track: 'novel', reason: '구두쇠 스크루지가 세 유령을 만나 변하는 이야기. 분량이 짧아 함께 읽기에 알맞습니다.' },
  { title: 'The Strange Case of Dr. Jekyll and Mr. Hyde', author: 'Stevenson', track: 'novel', reason: '한 사람 안의 선과 악을 다룬 짧은 고딕 소설입니다.' },
  { title: 'The Great Gatsby', author: 'Fitzgerald', track: 'novel', quote: 'So we beat on, boats against the current, borne back ceaselessly into the past.', reason: '1920년대 뉴욕의 화려함과 허무를 그린 소설. 마지막 문장이 유명합니다.' },
  { title: 'Adventures of Huckleberry Finn', author: 'Twain', track: 'novel', reason: '뗏목을 타고 강을 내려가는 헉과 짐의 여정. 당시의 차별적 표현이 나오므로 시대 배경과 함께 읽기를 권합니다.' },
  { title: 'Robinson Crusoe', author: 'Defoe', track: 'novel', reason: '무인도에서 홀로 살아남은 크루소의 생존 기록입니다.' },
  { title: "Gulliver's Travels", author: 'Swift', track: 'novel', reason: '소인국과 거인국을 여행하며 인간 사회를 풍자하는 이야기입니다.' },
  { title: 'The Yellow Wallpaper', author: 'Gilman', track: 'story', reason: '노란 벽지 방에 갇힌 화자의 일기 형식 단편. 짧지만 여운이 깁니다.' },
  { title: 'Metamorphosis', author: 'Kafka', track: 'story', reason: '어느 날 아침 벌레로 변한 그레고르의 이야기. 짧은 분량으로 깊은 질문을 던집니다.' },
  { title: 'Siddhartha', author: 'Hesse', track: 'novel', reason: '깨달음을 찾아 떠나는 청년 싯다르타의 여정. 문장이 간결하고 명상적입니다.' },
  { title: 'Frankenstein', author: 'Shelley', track: 'novel', quote: 'Beware; for I am fearless, and therefore powerful.', reason: '생명을 창조한 과학자와 괴물의 이야기. 편지와 고백이 겹겹이 이어집니다.' },
  { title: 'Dracula', author: 'Stoker', track: 'novel', reason: '일기와 편지로 엮은 흡혈귀 소설. 여러 화자의 문체를 비교할 수 있습니다.' },
  { title: 'Pride and Prejudice', author: 'Austen', track: 'novel', quote: 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.', reason: '엘리자베스와 다아시의 오해와 사랑. 반어적인 대화가 백미입니다.' },
  { title: 'Emma', author: 'Austen', track: 'novel', reason: '남의 연애를 주선하려다 일을 꼬이게 만드는 에마의 이야기입니다.' },
  { title: 'Persuasion', author: 'Austen', track: 'novel', reason: '8년 전 거절했던 사랑과 다시 마주한 앤의 이야기입니다.' },
  { title: 'Sense and Sensibility', author: 'Austen', track: 'novel', reason: '이성적인 언니와 감성적인 동생, 두 자매의 사랑과 선택을 그립니다.' },
  { title: 'Jane Eyre', author: 'Bront', track: 'novel', quote: 'I am no bird; and no net ensnares me', reason: '스스로 삶을 선택하는 여성 제인의 1인칭 성장 소설입니다.' },
  { title: 'Wuthering Heights', author: 'Bront', track: 'novel', reason: '황량한 언덕 저택에서 벌어지는 격정적인 사랑과 복수의 이야기입니다.' },
  { title: 'A Tale of Two Cities', author: 'Dickens', track: 'novel', quote: 'It was the best of times, it was the worst of times', reason: '프랑스 혁명기의 런던과 파리를 오가는 역사 소설입니다.' },
  { title: 'Great Expectations', author: 'Dickens', track: 'novel', reason: '고아 소년 핍이 신사가 되기까지의 성장 소설입니다.' },
  { title: 'Oliver Twist', author: 'Dickens', track: 'novel', reason: '런던 뒷골목에 내던져진 고아 올리버의 이야기. 당시 사회 문제를 엿볼 수 있습니다.' },
  { title: 'The Picture of Dorian Gray', author: 'Wilde', track: 'novel', quote: 'The only way to get rid of a temptation is to yield to it.', reason: '늙지 않는 청년과 대신 늙어 가는 초상화. 재치 있는 경구가 가득합니다.' },
  { title: 'The Scarlet Letter', author: 'Hawthorne', track: 'novel', reason: '청교도 마을에서 주홍 글자를 달고 살아가는 헤스터의 이야기입니다.' },
  { title: 'Heart of Darkness', author: 'Conrad', track: 'novel', quote: 'The horror! The horror!', reason: '콩고 강을 거슬러 오르는 항해로 제국주의의 어둠을 드러낸 중편입니다.' },
  { title: 'Dubliners', author: 'Joyce', track: 'story', reason: '더블린 사람들의 일상을 담은 단편 15편. 한 편씩 깊이 읽기 좋습니다.' },
  { title: 'Narrative of the Life of Frederick Douglass', author: 'Douglass', track: 'nonfiction', reason: '노예로 태어나 글을 깨치고 자유를 얻은 더글러스의 자서전입니다.' },
  { title: 'Moby Dick', author: 'Melville', track: 'novel', quote: 'Call me Ishmael.', reason: '흰 고래를 쫓는 에이해브 선장의 집념. 긴 분량과 풍부한 어휘에 도전해 보세요.' },
  { title: 'Walden', author: 'Thoreau', track: 'nonfiction', copy: true, quote: 'I went to the woods because I wished to live deliberately', reason: '숲속 오두막에서 2년을 산 기록. 삶을 돌아보게 하는 문장이 많아 필사하기 좋습니다.' },
  { title: 'Crime and Punishment', author: 'Dostoyevsky', track: 'novel', reason: '살인을 저지른 청년의 죄책감과 내면을 따라가는 심리 소설입니다.' },
  { title: 'The Brothers Karamazov', author: 'Dostoyevsky', track: 'novel', reason: '아버지의 죽음을 둘러싼 세 형제의 이야기. 신앙과 자유를 묻는 대작입니다.' },
  { title: 'Anna Karenina', author: 'Tolstoy', track: 'novel', quote: 'Happy families are all alike; every unhappy family is unhappy in its own way.', reason: '사랑과 사회 규범 사이에서 흔들리는 안나의 이야기. 첫 문장이 유명합니다.' },
  { title: 'War and Peace', author: 'Tolstoy', track: 'novel', reason: '나폴레옹 전쟁기 러시아 귀족 가문들의 삶을 그린 대하소설입니다.' },
  { title: 'The Count of Monte Cristo', author: 'Dumas', track: 'novel', reason: '억울하게 갇힌 청년의 탈옥과 치밀한 복수극입니다.' },
  { title: 'Les Misérables', author: 'Hugo', track: 'novel', reason: '장 발장의 삶을 따라 19세기 프랑스 사회를 그린 대작입니다.' },
  { title: 'Middlemarch', author: 'Eliot', track: 'novel', reason: '영국 지방 도시 사람들의 결혼과 이상을 촘촘히 엮은 장편입니다.' },
  { title: 'The Republic', author: 'Plato', track: 'nonfiction', reason: '정의란 무엇인가를 대화로 따져 묻는 철학 고전입니다.' },
  { title: 'Meditations', author: 'Marcus Aurelius', track: 'nonfiction', copy: true, reason: '로마 황제가 스스로에게 쓴 짧은 성찰 모음. 한 문단씩 필사하기 좋습니다.' },
  { title: 'The Prince', author: 'Machiavelli', track: 'nonfiction', reason: '권력을 얻고 지키는 법을 냉정하게 분석한 정치 고전입니다.' },

  { title: 'The Importance of Being Earnest', author: 'Wilde', track: 'drama', level: 3, reason: '이름을 둘러싼 오해로 웃음을 주는 희극. 대사가 짧고 재치 있습니다.' },
  { title: 'Romeo and Juliet', author: 'Shakespeare', track: 'drama', level: 4, reason: '원수 가문 두 연인의 비극. 운문과 산문이 섞인 대사를 비교해 볼 수 있습니다.' },
  { title: 'Macbeth', author: 'Shakespeare', track: 'drama', level: 4, reason: '예언에 사로잡혀 왕을 죽인 맥베스의 몰락. 셰익스피어 비극 가운데 가장 짧습니다.' },
  { title: 'Hamlet', author: 'Shakespeare', track: 'drama', level: 5, quote: 'To be, or not to be', reason: '복수와 망설임 사이에서 고뇌하는 왕자 햄릿의 비극입니다.' },

  { title: "A Child's Garden of Verses", author: 'Stevenson', track: 'poetry', level: 1, copy: true, reason: '어린 시절을 노래한 짧은 동시 모음. 운율이 또렷해 따라 쓰기 쉽습니다.' },
  { title: 'Songs of Innocence and of Experience', author: 'Blake', track: 'poetry', level: 2, copy: true, reason: '순수와 경험을 대비한 짧은 시들. ‘The Tyger’ 같은 유명한 시가 실려 있습니다.' },
  { title: 'The Raven', author: 'Poe', track: 'poetry', level: 3, copy: true, quote: 'Quoth the Raven', reason: '‘Nevermore’가 되풀이되는 음악적인 시. 소리 내어 읽으며 필사하기 좋습니다.' },
  { title: 'Poems by Emily Dickinson, Series One', author: 'Dickinson', track: 'poetry', level: 3, copy: true, reason: '짧은 행에 깊은 생각을 담은 디킨슨의 시. 한 편씩 옮겨 적기 알맞습니다.' },
  { title: "A Boy's Will", author: 'Frost', track: 'poetry', level: 3, copy: true, reason: '로버트 프로스트의 첫 시집. 자연과 일상을 담백하게 노래합니다.' },
  { title: 'The Prophet', author: 'Gibran', track: 'poetry', level: 3, copy: true, reason: '사랑, 일, 자유 같은 삶의 주제를 짧은 산문시로 풀어낸 책입니다.' },
  { title: 'Leaves of Grass', author: 'Whitman', track: 'poetry', level: 4, copy: true, reason: '자유시의 출발점. 긴 호흡의 행을 따라 쓰며 리듬을 느껴 보세요.' },
  { title: 'Sonnets from the Portuguese', author: 'Browning', track: 'poetry', level: 4, copy: true, reason: '사랑을 노래한 소네트 44편. 14행 형식을 익히기 좋습니다.' },
  { title: 'Rubáiyát of Omar Khayyám', author: 'Omar', track: 'poetry', level: 4, copy: true, reason: '인생의 덧없음을 노래한 4행시 모음의 영어 번역입니다.' },
  { title: "Shakespeare's Sonnets", author: 'Shakespeare', track: 'poetry', level: 5, copy: true, reason: '셰익스피어 소네트 154편. 옛 영어 표현에 도전하는 필사용 시집입니다.' },
  { title: 'Paradise Lost', author: 'Milton', track: 'poetry', level: 5, copy: true, reason: '타락한 천사와 인간의 이야기를 그린 장편 서사시입니다.' },
];
